name: tacca
env:
  DATABASE: ${{ secrets.DATABASE }}
  HOST: ${{ secrets.HOST }}
  PASSWORD: ${{ secrets.PASSWORD }}
  PORT: ${{ secrets.PORT }}
  USER: ${{ secrets.USER }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install and run
        run: |
          npm install --legacy-peer-deps
          npm run build
        env:
          CI: true
